version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      next-react:
        patterns: ['next', 'eslint-config-next', 'react', 'react-dom', '@types/react*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
